-
    all:
        hosts:
            webservers:
                hosts:
                    webserver1:
                        ansible_connection:
                        ansible_host: 10.0.1.1
                        ansible_port: 22
                        ansible_ssh_private_key_file: ./keys/private.ppk
#                    webserver2:
#                        ansible_connection:
#                        ansible_host: 10.0.1.1
#                        ansible_port: 22
#                        ansible_ssh_private_key_file: ./keys/private.ppk
            dbservers:
                hosts:
                    dbserver1:
                        ansible_connection:
                        ansible_host: 10.0.1.1
                        ansible_port: 22
                        ansible_ssh_private_key_file: ./keys/private.ppk
#                    dbserver2:
#                        ansible_connection:
#                        ansible_host: 10.0.1.1
#                        ansible_port: 22
#                        ansible_ssh_private_key_file: ./keys/private.ppk
            



# https://docs.ansible.com/ansible/2.4/intro_inventory.html
#https://www.cyberciti.biz/faq/define-ssh-key-per-host-using-ansible_ssh_private_key_file/