---
- name: Install required Python libraries
  pip:
    name: ['flask','flask-mysql']
    state: present
#birden fazla action çalıştırabilmek için block kullanılır
- block:
  - name: Remove App.py if it exists 
    shell:
      cmd: '[ -e /opt/app.py ] && rm /opt/app.py' # bu komut yerine absend kullanamk daha doğru olacaktır. test etmek için yazıldı
    register: swap_exists
    # ignore_errors: true
    failed_when: swap_exists.rc != 1 and swap_exists.rc != 0
  - name: Copy source code from template
    template:
      src: ./templates/app.py.j2
      dest: /opt/app.py
      owner: root
      group: root
      mode: 644
#    delegate_to: 127.0.0.1  # ilgili komutu farklı bir host ta yönlendirmek için kullanılır.
  rescue:
    - debug:
        msg: 'I caught an error, can do stuff here to fix it, :-)'

# - hosts: 127.0.0.1
#   connection: local
#   tasks:
#     - name: copy local
#       template:
#         src: ./templates/app.py.j2
#         dest: ./templates/app.py

- name: Start web server
  shell: FLASK_APP=/opt/app.py flask run --host=0.0.0.0 -p 3000

