---
- hosts: localhost
  vars:
    - windows_servers:
        - wserver1: {name: wserver1murat, osmanageddiskname: wserver1mandisk1murat, ninterface: nimuratwserver1}
        - wserver2: {name: wserver2murat, osmanageddiskname: wserver2mandisk1murat, ninterface: nimuratwserver2}

    - linux_servers:
        - lserver1: {name: lserver1murat, osmanageddiskname: lserver1mandisk1murat, ninterface: nimuratlserver1}
        - lserver2: {name: lserver2murat, osmanageddiskname: lserver2mandisk1murat, ninterface: nimuratlserver2}

#    - resource_group: MCTEST # ------> host_vars a taşındı
    - linux_user: muratcabuk
    - windows_user: muratcabuk
    - vm_password: Passw0rd-1
    - vn_name: testvirtualnetworkmurat
    - sn_name: testsubnetmurat
    - sa_name: teststoragemurat
    - aswindows_name: testaysetwindowsmurat
    - aslinux_name: testaysetlinuxmurat
    - network_interface_name: testinterfacemurat

  tasks:

    - name: create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: westeurope
        state: present
      tags: 
        - 1

    - name: create a virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vn_name }}"
        address_prefixes_cidr:
          - "10.0.0.0/16"
        # dns_servers:
        #   - "127.0.0.1"
        state: present
      register: vn_result
      tags: 
        - 2

    - debug:
        msg: "virtual network is created. {{vn_result}}"


    - name: create a subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ vn_name }}"
        name: "{{ sn_name }}"
        address_prefix: "10.0.1.0/24"
        state: present    
      register: sn_result
      tags: 
        - 3

    - debug:
        msg: "subnet is created. {{sn_result}}"

    - name: Create virtual network inteface cards for windows VMs
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.ninterface }}"
        virtual_network: "{{ vn_name }}"
        subnet: "{{ sn_name }}"
        state: present
        with_items: "{{ windows_servers }}"
#        register: vni_result
#        tags: 
#          - 4

    - debug:
        msg: "virtual network inteface is created for windows"


    - name: Create virtual network inteface cards for linux VMs
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.ninterface }}"
        virtual_network: "{{ vn_name }}"
        subnet: "{{ sn_name }}"
        state: present
        with_items: "{{ linux_servers }}"
#        register: vni_result
#        tags: 
#          - 4

    - debug:
        msg: "virtual network inteface is created for linux"


        


    - name: create a storage account
      azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ sa_name }}"
        account_type: Standard_LRS
        kind: StorageV2
        state: present
      register: sa_result
      tags: 
        - 5

    - debug:
        msg: "storage account is created. {{ sa_result }}"

    - name: Create managed windows system disk from page blob
      azure_rm_manageddisk:
        name: "{{ item.osmanageddiskname }}"
        resource_group:  "{{ resource_group }}"
        create_option: empty
        os_type: windows
        storage_account_type: Standard_LRS
        state: present
      with_items: "{{ windows_servers }}"
      register: windows_mandisk_result
      tags: 
        - 6

    - debug:
        msg: "Windows Managed Disks are created: {{ windows_mandisk_result }}"

      
    - name: Create managed linux system disk from page blob
      azure_rm_manageddisk:
        name: "{{ item.osmanageddiskname }}"
        resource_group:  "{{ resource_group }}"
        create_option: empty
        os_type: linux
        storage_account_type: Standard_LRS
        state: present
      with_items: "{{ linux_servers }}"
      register: linux_mandisk_result
      tags: 
        - 7

    - debug:
        msg: "Linux Managed Disks are created: {{ linux_mandisk_result }}"


    - name: Create an availability set with default options for windows
      azure_rm_availabilityset:
        name: "{{aswindows_name}}"
        resource_group: "{{ resource_group }}"
        state: present
      register: aswindows_result
      tags: 
        - 8

    - debug:
        msg: "Availability set for windows is created. {{ aswindows_result }}"

    - name: Create an availability set with default options for linux
      azure_rm_availabilityset:
        name: "{{aslinux_name}}"
        resource_group: "{{ resource_group }}"
        state: present
      register: aslinux_result
      tags: 
        - 9

    - debug:
        msg: "Availability set for linux is created. {{ aslinux_result }}"



    - name: Create a Windows VM with existing storage account
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        admin_username: "{{ windows_user }}"
        admin_password: "{{ vm_password }}"
        vm_size: Standard_B1s
        storage_account: "{{ sa_name }}"
        os_type: Windows
        public_ip_allocation_method: Dynamic
        # subnet_name: {{ testsubnet }}
        # virtual_network_name: {{ testvirtualnetwork }}"
        network_interfaces: "{{ item.ninterface }}"
        state: present
        image:
          offer: WindowsServer
          publisher: MicrosoftWindowsServer
          sku: 2016-Datacenter
          version: latest
      with_items: "{{ windows_servers }}"
      register: vmwin_result
      tags: 
        - 10
      
    - debug:
        msg: "Windows VMs are created: {{ vmwin_result }}"

    - name: Create a Linux VM with existing storage account
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        admin_username: "{{ linux_user }}"
        admin_password: "{{ vm_password }}"
        ssh_password_enabled: true
        # ssh_public_keys:
        #   - path: /home/{{linux_user}}/.ssh/authorized_keys
        #     key_data: <your-key-data>
        vm_size: Standard_B1s
        storage_account: "{{ sa_name }}"
        os_type: Linux
        public_ip_allocation_method: Dynamic
        # subnet_name: "{{ testsubnet }}"
        # virtual_network_name: "{{ testvirtualnetwork }}"
        network_interfaces: "{{ network_interface_name }}"
        state: present
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
      with_items: "{{ Linux_servers }}"
      register: vmlin_result
      tags: 
        - 11
      
    - debug:
        msg: "Linux VMs are created: {{vmlin_result}}"

