---
- name: install requirements 1
  apt:
    name: ['python','python3-pip', 'python3-dev','nginx']
    state: present

- name: install requirements 2
  apt:
    name: [ 'virtualenv','python-setuptools', 'python3-venv']
    state: present


- name: Wait and notify handler
  shell:
    cmd: sleep 3
  async: 20
  poll: 0
  register: my_task
  notify: Done Handler

- name: Check on async task
  async_status:
    jid: "{{ my_task.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 10

# handler handlers klasöründe
