---
- name: install requirements 1
  apt:
    name: ['python','python3-pip', 'python3-dev','nginx']
    state: present



- name: install requirements 2
  apt:
    name: [ 'virtualenv','python-setuptools', 'python3-venv']
    state: present


- name: Wait and notify handler
  shell:
    cmd: sleep 5
  # async: 120
  # poll: 0
  register: my_task
  notify: Done Handler

# handler handlers klasöründe
