---
- name: install requirements 1
  apt:
    name: ['python','python3-pip', 'python3-dev','nginx']
    state: changed
  async: 120
  poll: 0
  notify: Done Handler


- name: install requirements 2
  apt:
    name: [ 'virtualenv','python-setuptools', 'python3-venv']
    state: changed
  async: 120
  poll: 0
  notify: Done Handler

# handler handlers klasöründe
