---
- name: Deloy a web app
  hosts: all
  tasks:
    - name: install requirements
      apt:
        name: ['python','python3-pip', 'python3-dev','nginx', 'virtualenv','python-setuptools', 'python3-venv']
        state: present

    - include: tasks/deploydb.yml
    - include: tasks/deployweb.yml


